export const motorFinanceProviders = [
  { name: "Select Provider", warning: false },
  { name: "Admiral", warning: true },
  { name: "Advantage Finance", warning: true },
  { name: "Aldermore", warning: false },
  { name: "Alphera", warning: false },
  { name: "Audi (VW Financial Services)", warning: false },
  { name: "Autolend", warning: true },
  { name: "Bamboo", warning: false },
  { name: "Barclays Partner Finance", warning: false },
  { name: "Billing Finance", warning: true },
  { name: "Black Horse", warning: false },
  { name: "Blue Motor Finance", warning: false },
  { name: "BMW Financial Services (inc. Mini)", warning: false },
  { name: "CA Auto Finance", warning: false },
  { name: "CarCashPoint", warning: true },
  { name: "CarFinance 247", warning: false },
  { name: "CarMoney", warning: false },
  { name: "Carmoola", warning: true },
  { name: "Close Brothers", warning: false },
  { name: "FCA Automotive", warning: false },
  { name: "Finio Loans", warning: false },
  { name: "First Response Finance", warning: true },
  { name: "Ford Credit Europe (FCE)", warning: false },
  { name: "Hitachi Capital (Novuna)", warning: false },
  { name: "Honda Financial Services", warning: false },
  { name: "Hyundai Finance", warning: false },
  { name: "JBR Capital", warning: false },
  { name: "Kia Finance", warning: false },
  { name: "Lendable", warning: true },
  { name: "Lombard Asset Finance", warning: false },
  { name: "Mallard Finance", warning: true },
  { name: "Mann Island Finance", warning: false },
  { name: "Marsh Finance", warning: false },
  { name: "Mercedes-Benz Financial Services", warning: false },
  { name: "Mobilize", warning: false },
  { name: "Moneybarn", warning: true },
  { name: "Moneyway", warning: false },
  { name: "MotoNovo", warning: false },
  { name: "MotorKitty", warning: false },
  { name: "Northridge", warning: false },
  { name: "Novuna", warning: false },
  { name: "Oodle Car Finance", warning: true },
  { name: "Oplo", warning: true },
  { name: "Paragon", warning: false },
  { name: "PCF Bank", warning: false },
  { name: "PSA (Stellantis)", warning: false },
  { name: "RCI (now Mobilize)", warning: false },
  { name: "Santander", warning: false },
  { name: "Shawbrook", warning: false },
  { name: "Specialist Motor Finance", warning: true },
  { name: "Startline Motor Finance", warning: false },
  { name: "Stellantis", warning: false },
  { name: "Tandem", warning: true },
  { name: "Toyota Financial Services", warning: false },
  { name: "V12 Vehicle Finance", warning: true },
  { name: "Vauxhall Finance", warning: false },
  { name: "Volkswagen Financial Services", warning: false },
  { name: "Volvo Car Financial Services", warning: false },
  { name: "Zopa", warning: false },
  { name: "Other", warning: false },
];
