export const motorFinanceProviders = [
  "Select Provider",
  "Admiral",
  "Advantage Finance",
  "Aldermore",
  "Alphera",
  "Audi (VW Financial Services)",
  "Autolend",
  "Bamboo",
  "Barclays Partner Finance",
  "Billing Finance",
  "Black Horse",
  "Blue Motor Finance",
  "BMW Financial Services (inc. Mini)",
  "CA Auto Finance ",
  "CarCashPoint",
  "CarFinance 247",
  "CarMoney",
  "Carmoola",
  "Close Brothers",
  "FCA Automotive",
  "Finio Loans",
  "First Response Finance",
  "Ford Credit Europe (FCE)",
  "Hitachi Capital (Novuna)",
  "Honda Financial Services",
  "Hyundai Finance",
  "JBR Capital",
  "Kia Finance",
  "Lendable",
  "Lombard Asset Finance",
  "Mallard Finance",
  "Mann Island Finance",
  "Marsh Finance",
  "Mercedes-Benz Financial Services",
  "Mobilize",
  "Moneybarn",
  "Moneyway",
  "MotoNovo",
  "MotorKitty",
  "Northridge",
  "Novuna",
  "Oodle Car Finance",
  "Oplo",
  "Paragon",
  "PCF Bank",
  "PSA (Stellantis)",
  "RCI (now Mobilize)",
  "Santander",
  "Shawbrook",
  "Specialist Motor Finance",
  "Startline Motor Finance",
  "Stellantis",
  "Tandem",
  "Toyota Financial Services",
  "V12 Vehicle Finance",
  "Vauxhall Finance",
  "Volkswagen Financial Services",
  "Volvo Car Financial Services",
  "Zopa",
  "Other",
];
