export const financeProviders = [
  { name: "Select your provider", warning: false },
  { name: "Admiral", email: "loansquality@admiralgroup.co.uk", warning: true },
  { name: "Advantage Finance", email: "complaints@advantage-finance.co.uk", warning: true },
  { name: "Aldermore", email: "commissionenquiries@motonovofinance.com", warning: false },
  { name: "Alphera", email: "commissiondisclosureenquiries@bmwfin.com", warning: false },
  { name: "Audi (VW Financial Services)", email: "commissionclaims@vwfs.co.uk", warning: false },
  { name: "Autolend", email: "complaint@autolend.co.uk", warning: true },
  { name: "Bamboo", email: "complaints@bambooloans.com", warning: false },
  { name: "Barclays Partner Finance", email: "bpfmotorcommissioncomplaints@barclays.com", warning: false },
  { name: "Billing Finance", email: "complaints@billingfinance.co.uk", warning: true },
  { name: "Black Horse", email: "mse.motorcommission@blackhorse.co.uk", warning: false },
  { name: "Blue Motor Finance", email: "complaints@bluemotorfinance.co.uk", warning: false },
  { name: "BMW Financial Services (inc. Mini)", email: "commissiondisclosureenquiries@bmwfin.com", warning: false },
  { name: "CA Auto Finance", email: "customer-relations@ca-autobank.com", warning: false },
  { name: "CarCashPoint", email: "complaints@carcashpoint.com", warning: true },
  { name: "CarFinance 247", email: "customercare@carfinance247.co.uk", warning: false },
  { name: "CarMoney", email: "complaints@carmoney.co.uk", warning: false },
  { name: "Carmoola", email: "complaints@carmoola.co.uk", warning: true },
  { name: "Close Brothers", email: "complaintsMF@closebrothers.com", warning: false },
  { name: "FCA Automotive", email: "customer-relations@ca-autobank.com", warning: false },
  { name: "Finio Loans", email: "complaints@oakbrookfinance.com", warning: false },
  { name: "First Response Finance", email: "complaints@frfl.co.uk", warning: true },
  { name: "Ford Credit Europe (FCE)", email: "custrel@ford.com", warning: false },
  { name: "Hitachi Capital (Novuna)", email: "customerservice@novunapersonalfinance.co.uk", warning: false },
  { name: "Honda Financial Services", email: "hfe.customerservice@honda-eu.com", warning: false },
  { name: "Hyundai Finance", email: "commissionqueries@hyundaifinanceuk.co.uk", warning: false },
  { name: "JBR Capital", email: "complaints@jbrcapital.com", warning: false },
  { name: "Kia Finance", email: "commissionqueries@kiafinanceuk.co.uk", warning: false },
  { name: "Lendable", email: "complaint@lendable.co.uk", warning: true },
  { name: "Lombard Asset Finance", email: "generalenquiries@lombard.co.uk", warning: false },
  { name: "Mallard Finance", email: "sales@mallardfinance.co.uk", warning: true },
  { name: "Mann Island Finance", email: "complaints@mannisland.co.uk", warning: false },
  { name: "Marsh Finance", email: "enquiries@marshfinance.co.uk", warning: false },
  { name: "Mercedes-Benz Financial Services", email: "mbfs-commissions@mercedes-benz.com", warning: false },
  { name: "Mobilize", email: "motorcommissionenquiries@mobilize-fs.com", warning: false },
  { name: "Moneybarn", email: "complaints@moneybarn.com", warning: true },
  { name: "Moneyway", email: "complaints@securetrustbank.co.uk", warning: false },
  { name: "MotoNovo", email: "commissionenquiries@motonovofinance.com", warning: false },
  { name: "MotorKitty", email: "complaints@motorkitty.co.uk", warning: false },
  { name: "Northridge", email: "northridgecomplaints@northridgeuk.com", warning: false },
  { name: "Novuna", email: "customerservice@novunapersonalfinance.co.uk", warning: false },
  { name: "Oodle Car Finance", email: "customer.relations@oodlefinance.com", warning: true },
  { name: "Oplo", email: "complaints@myoplo.co.uk", warning: true },
  { name: "Paragon", email: "bank.complaints@paragonbank.co.uk", warning: false },
  { name: "PCF Bank", email: "complaints@pcf.bank", warning: false },
  { name: "PSA (Stellantis)", email: "commissiondisclosure@stellantis-finance.com", warning: false },
  { name: "RCI (now Mobilize)", email: "motorcommissionenquiries@mobilize-fs.com", warning: false },
  { name: "Santander", email: "commissionqueries@santanderconsumer.co.uk", warning: false },
  { name: "Shawbrook", email: "customercare.team@shawbrook.co.uk", warning: false },
  { name: "Specialist Motor Finance", email: "customerservices@smfmotor.com", warning: true },
  { name: "Startline Motor Finance", email: "commission@startlinemotorfinance.com", warning: false },
  { name: "Stellantis", email: "commissiondisclosure@stellantis-finance.com", warning: false },
  { name: "Tandem", email: "motorfinance@tandem.co.uk", warning: true },
  { name: "Toyota Financial Services", email: "commissioncomplaints@toyota-fs.com", warning: false },
  { name: "V12 Vehicle Finance", email: "complaints@v12finance.com", warning: true },
  { name: "Vauxhall Finance", email: "commissiondisclosure@stellantis-finance.com", warning: false },
  { name: "Volkswagen Financial Services", email: "commissionclaims@vwfs.co.uk", warning: false },
  { name: "Volvo Car Financial Services", email: "commissionqueries@vcfsuk.co.uk", warning: false },
  { name: "Zopa", email: "complaints@zopa.com", warning: false },
];
